"""empty message

Revision ID: 173eb7f06ef5
Revises: b4af14f7b89e
Create Date: 2025-04-22 17:28:33.257461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173eb7f06ef5'
down_revision = 'b4af14f7b89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Character_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'character', ['Character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Character_id')

    # ### end Alembic commands ###
