"""empty message

Revision ID: 1d53fd44082c
Revises: 68c1f1d2615e
Create Date: 2025-04-22 17:17:54.791325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d53fd44082c'
down_revision = '68c1f1d2615e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_Favorite_fkey', type_='foreignkey')
        batch_op.drop_column('Favorite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Favorite', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_Favorite_fkey', 'favorite', ['Favorite'], ['id'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
