"""empty message

Revision ID: 6e12b885086d
Revises: 9cccb836de56
Create Date: 2025-04-22 18:33:38.728823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e12b885086d'
down_revision = '9cccb836de56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_character')
    op.drop_table('favorite_vehicle')
    op.drop_table('character_vehicle')
    op.drop_table('favorite_planet')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key(None, 'favorite', ['favorite_id'], ['id'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key(None, 'favorite', ['favorite_id'], ['id'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'favorite', ['favorite_id'], ['id'])
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('favorite_id')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('favorite_id')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('favorite_id')

    op.create_table('favorite_planet',
    sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], name='favorite_planet_favorite_id_fkey'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorite_planet_planet_id_fkey'),
    sa.PrimaryKeyConstraint('favorite_id', 'planet_id', name='favorite_planet_pkey')
    )
    op.create_table('character_vehicle',
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='character_vehicle_character_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='character_vehicle_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('character_id', 'vehicle_id', name='character_vehicle_pkey')
    )
    op.create_table('favorite_vehicle',
    sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], name='favorite_vehicle_favorite_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='favorite_vehicle_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('favorite_id', 'vehicle_id', name='favorite_vehicle_pkey')
    )
    op.create_table('favorite_character',
    sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorite_character_character_id_fkey'),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], name='favorite_character_favorite_id_fkey'),
    sa.PrimaryKeyConstraint('favorite_id', 'character_id', name='favorite_character_pkey')
    )
    # ### end Alembic commands ###
