"""empty message

Revision ID: 78ea848c776e
Revises: 173eb7f06ef5
Create Date: 2025-04-22 17:29:45.574884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ea848c776e'
down_revision = '173eb7f06ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_Character_id_fkey', type_='foreignkey')
        batch_op.drop_column('Character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Character_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('planet_Character_id_fkey', 'character', ['Character_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###
