"""empty message

Revision ID: 9cccb836de56
Revises: 25e11eadc73a
Create Date: 2025-04-22 18:32:29.967599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cccb836de56'
down_revision = '25e11eadc73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_vehicle',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'vehicle_id')
    )
    op.create_table('favorite_character',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ),
    sa.PrimaryKeyConstraint('favorite_id', 'character_id')
    )
    op.create_table('favorite_planet',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('favorite_id', 'planet_id')
    )
    op.create_table('favorite_vehicle',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorite.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('favorite_id', 'vehicle_id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_favorite_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('character_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('favorite_id')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('planet_favorite_id_fkey', type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('favorite_id')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('vehicle_favorite_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('vehicle_character_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('favorite_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('vehicle_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.create_foreign_key('vehicle_favorite_id_fkey', 'favorite', ['favorite_id'], ['id'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('planet_favorite_id_fkey', 'favorite', ['favorite_id'], ['id'])
        batch_op.create_foreign_key('planet_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('character_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key('character_favorite_id_fkey', 'favorite', ['favorite_id'], ['id'])

    op.drop_table('favorite_vehicle')
    op.drop_table('favorite_planet')
    op.drop_table('favorite_character')
    op.drop_table('character_vehicle')
    # ### end Alembic commands ###
