"""empty message

Revision ID: ee56c14072b5
Revises: 3242a5b7958a
Create Date: 2025-04-22 17:57:37.576188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee56c14072b5'
down_revision = '3242a5b7958a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_vehicle',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'vehicle_id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_column('vehicle_id')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('vehicle_character_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('vehicle_character_id_fkey', 'character', ['character_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('character_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])

    op.drop_table('character_vehicle')
    # ### end Alembic commands ###
